@baseUrl = http://localhost:3000
@categoryId = 698ea1788f0b1838ceb9ae71
@taskId = 698ea2058f0b1838ceb9ae72

### List categories
GET {{baseUrl}}/api/categories

### Create category
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Home"
}

### Update category
PUT {{baseUrl}}/api/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "Church"
}

### Delete category
DELETE {{baseUrl}}/api/categories/{{categoryId}}

### List tasks
GET {{baseUrl}}/api/tasks

### Create task
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
  "title": "Make bed",
  "description": "Make the bed neatly",
  "categoryId": "698e98c42942c5ae0ccb96ff",
  "isCompleted": false
}

### Update task
PUT {{baseUrl}}/api/tasks/{{taskId}}
Content-Type: application/json

{
  "title": "Pack lunch",
  "description": "Pack your lunch for tomorrow",
  "isCompleted": true
}

### Delete task
DELETE {{baseUrl}}/api/tasks/{{taskId}}
