@baseUrl = http://localhost:3000
@categoryId = 69881089e5d9c27ee948251a
@taskId = 698bd4937224a298f4aebb74

### List categories
GET {{baseUrl}}/api/categories

### Create category
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "School"
}

### Update category
PUT {{baseUrl}}/api/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "School"
}

### Delete category
DELETE {{baseUrl}}/api/categories/{{categoryId}}

### List tasks
GET {{baseUrl}}/api/tasks

### Create task
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
  "title": "Make bed",
  "description": "Make the bed neatly",
  "categoryId": "69881807c72a2298cb7d44f1",
  "isCompleted": false
}

### Update task
PUT {{baseUrl}}/api/tasks/{{taskId}}
Content-Type: application/json

{
  "title": "Make bed (Updated)",
  "description": "Tidy and straighten sheets",
  "isCompleted": true
}

### Delete task
DELETE {{baseUrl}}/api/tasks/{{taskId}}
